name: Crear APK de Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout proyecto
        uses: actions/checkout@v4

      - name: Exportar APK con Godot
        uses: firebelley/godot-export@v7.0.0
        with:
          relative_project_path: "."
          presets_to_export: "Android"
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: Wrestling2D_APK
          path: "**/*.apk"
